Add support for Flexmark TOC extension (#63)
kiranshila/cybermonday pull request #64
Opened 2022-09-08 02:53 UTC by stelcodes

This patch adds a new dependency on flexmark-ext-toc and adds the extension to the Flexmark parser. This enables a table of contents node to be included in the markdown IR by including a line of `[TOC]` in the markdown content. Optionally a list of heading levels to be included can be specified like so: `[TOC levels=1-3,5]`. This new IR node is called :markdown/table-of-contents.

The patch also includes a translation from this node into Hiccup. This lower function is unique because it requires the full IR representation and thus requires two arguments. It analyzes the IR's headings and creates a nested unordered-list which link to the headings via their `id` values which were already created in the heading lower function.

Fixes #63

2022-09-10 00:28 UTC, stelcodes commented
An alternative to adding the lowering function I came with to Cybermonday is just to have a lowering function that returns `nil` and leave the implementation up to the user via `:lower-fns`.

2022-09-14 14:43 UTC, kiranshila commented
Wow this rocks! Thank you for this. I think I don't mind not having 100% parity with CLJS, as long as it's documented. Can you add this new node to the [docs](https://github.com/kiranshila/cybermonday/blob/master/doc/02-AST.md) and document that it's Java-only?

2022-09-14 14:45 UTC, kiranshila commented
Ah, we need a ` #?(::cljs ...))` for that Java.Integer import

2022-09-14 14:47 UTC, kiranshila requested changes

2022-09-14 15:56 UTC, stelcodes commented
Hey thanks for taking a look! I will update this soon :partying_face:

2022-11-24 00:29 UTC, kiranshila commented
Sorry for the close - that was an accident. Any success with these fixes?

2022-12-05 22:02 UTC, stelcodes commented
@kiranshila hey sorry about that, got really distracted with life stuff. I'm working on an update now.

2022-12-06 06:21 UTC, stelcodes commented
Just rebased on current HEAD

2022-12-07 00:25 UTC, kiranshila commented
We'll have to gate the tests behind a `#?(:clj ...` as well

2022-12-10 18:36 UTC, stelcodes commented
Updated! Should work now.

2022-12-12 20:33 UTC, merged

2022-12-12 20:33 UTC, kiranshila commented
Thanks for the work, Stel!